library DDData;

uses
  FastMM4 in '..\puer\pubUnit\FastMM4.pas',
  FastMM4Messages in '..\puer\pubUnit\FastMM4Messages.pas',
  puer.Collections in '..\puer\pubUnit\puer.Collections.pas',
  puer.DateFormatSet in '..\puer\pubUnit\puer.DateFormatSet.pas',
  puer.Json.JsonDataObjects in '..\puer\pubUnit\puer.Json.JsonDataObjects.pas',
  puer.SyncObjs in '..\puer\pubUnit\puer.SyncObjs.pas',
  puer.System in '..\puer\pubUnit\puer.System.pas',
  puer.FileUtils in '..\puer\pubUnit\puer.FileUtils.pas',
  puer.TTS in '..\puer\pubUnit\puer.TTS.pas',
  UPrDbConnInter in '..\puer\interface\UPrDbConnInter.pas',
  UPrEMailInter in '..\puer\interface\UPrEMailInter.pas',
  UPrSmsInter in '..\puer\interface\UPrSmsInter.pas',
  UPrLogInter in '..\puer\interface\UPrLogInter.pas',
  UDDTopologyData in '..\classes\dataDigger\UDDTopologyData.pas',
  UDDTopologyDataJson in '..\classes\dataDigger\UDDTopologyDataJson.pas',
  UDDRequestData in '..\classes\dataDigger\UDDRequestData.pas',
  UDDDeviceRealData in '..\classes\dataDigger\UDDDeviceRealData.pas',
  UDDLogData in '..\classes\dataDigger\UDDLogData.pas',
  UDDUserData in '..\classes\dataDigger\UDDUserData.pas',
  UDDFileListData in '..\classes\dataDigger\UDDFileListData.pas',
  UDDMeterData in '..\classes\dataDigger\UDDMeterData.pas',
  UDDDeviceModelData in '..\classes\model\UDDDeviceModelData.pas',
  UDDParamData in '..\classes\model\UDDParamData.pas',
  UDDHourValueData in '..\classes\dataDigger\UDDHourValueData.pas',
  UDDHourDosageData in '..\classes\dataDigger\UDDHourDosageData.pas',
  UEnergyTypeData in '..\classes\dataDigger\UEnergyTypeData.pas',
  UDDBrokerData in '..\classes\dataDigger\UDDBrokerData.pas',
  UDDDeviceData in '..\classes\dataDigger\UDDDeviceData.pas',
  UDDGatewayData in '..\classes\dataDigger\UDDGatewayData.pas',
  UDDChangeData in '..\classes\dataDigger\UDDChangeData.pas',
  UOnLineData in '..\classes\dataDigger\UOnLineData.pas',
  UBrokerInfoData in '..\classes\dataDigger\UBrokerInfoData.pas',
  UDDDeviceDataXml in '..\classes\dataDigger\UDDDeviceDataXml.pas',
  UDDDataCtrl in 'UDDDataCtrl.pas',
  UDDData.Request in 'UDDData.Request.pas',
  UDDData.DeviceRealData in 'UDDData.DeviceRealData.pas',
  UDDData.TopoData in 'UDDData.TopoData.pas',
  UDDData.Log in 'UDDData.Log.pas',
  UDDData.Meter in 'UDDData.Meter.pas',
  UDDData.DeviceChange in 'UDDData.DeviceChange.pas',
  UEnergyUseData in '..\classes\dataDigger\UEnergyUseData.pas',
  UDDData.User in 'UDDData.User.pas',
  UDDData.Config in 'UDDData.Config.pas',
  UDDChangeDataXml in '..\classes\dataDigger\UDDChangeDataXml.pas',
  UDDCommDataInfoData in '..\classes\dataDigger\UDDCommDataInfoData.pas';

{$R *.res}

begin
end.
